In [54]:
import numpy as np
import pandas as pd

In [55]:
df=pd.read_csv(r"C:\Users\DELL\Downloads\Data Science Sai Charan\DATA SETS\Data.csv")

In [56]:
df.head(10)

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90
5  26.27  59.44  1012.23  58.77  443.67
6  15.89  43.96  1014.02  75.24  467.35
7   9.48  44.71  1019.12  66.43  478.42
8  14.64  45.00  1021.78  41.25  475.98
9  11.74  43.56  1015.14  70.72  477.50

In [57]:
df.shape

(9568, 5)

In [58]:
df.isna().sum()

AT    0
V     0
AP    0
RH    0
PE    0
dtype: int64

In [59]:
X=df.iloc[:,:-1].values

print(X)

y=df.iloc[:,-1:].values

print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[[463.26]
 [444.37]
 [488.56]
 ...
 [429.57]
 [435.74]
 [453.28]]


In [60]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(X, y , test_size=0.2, random_state=0)

In [61]:
x_train

array([[  11.22,   43.13, 1017.24,   80.9 ],
       [  13.67,   54.3 , 1015.92,   75.42],
       [  32.84,   77.95, 1014.68,   45.8 ],
       ...,
       [  16.81,   38.52, 1018.26,   75.21],
       [  12.8 ,   41.16, 1022.43,   86.19],
       [  32.32,   67.9 , 1006.08,   37.93]])

In [62]:
y_train

array([[473.93],
       [467.87],
       [431.97],
       ...,
       [459.01],
       [462.72],
       [428.12]])

In [63]:
#Standard scalar or Min max scalar we can do
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [64]:

x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
y_train = sc.fit_transform(y_train)

In [65]:
y_train

array([[ 1.15069786],
       [ 0.79540777],
       [-1.30936356],
       ...,
       [ 0.27595724],
       [ 0.49346982],
       [-1.53508417]])

In [66]:
x_train

array([[-1.13572795, -0.88685592,  0.67357894,  0.52070558],
       [-0.80630243, -0.00971567,  0.45145467,  0.14531044],
       [ 1.77128416,  1.84743445,  0.24279248, -1.88374143],
       ...,
       [-0.38409993, -1.24886277,  0.84522042,  0.13092486],
       [-0.9232821 , -1.04155299,  1.54693117,  0.8830852 ],
       [ 1.70136528,  1.05824381, -1.20438076, -2.42285818]])

In [67]:
x_test

array([[ 1.20924389,  1.84743445, -0.61878043, -0.28968211],
       [-0.29401214, -0.39528045,  1.39211729,  0.76937061],
       [-0.64629575, -0.88607065,  1.00508258,  1.77019599],
       ...,
       [-0.99857936, -0.74629361,  1.76737267,  1.02146078],
       [ 1.02368993, -0.50992904, -1.64526378, -0.96443434],
       [-0.32090402, -1.13342892, -1.03442205,  0.0651622 ]])

In [68]:
from sklearn.tree import DecisionTreeRegressor
regressor=DecisionTreeRegressor()
regressor.fit(x_train,y_train)

DecisionTreeRegressor()

In [69]:
y_pred=regressor.predict(x_test)

In [70]:
y_pred

array([-1.34981739,  0.3099619 ,  0.33751741, ...,  1.00588491,
       -0.96990323,  0.48350294])

In [71]:
y_pred = sc.inverse_transform(y_pred.reshape(-1, 1))


In [72]:
print(y_pred)


[[431.28]
 [459.59]
 [460.06]
 ...
 [471.46]
 [437.76]
 [462.55]]


In [73]:

from sklearn.metrics import r2_score
print(f'The r2 score is : {r2_score(y_test , y_pred)}')

The r2 score is : 0.9225521033363815
