In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [3]:
df=pd.read_csv(r"C:\Users\DELL\Downloads\Data Science Sai Charan\DATA SETS\Advertising.csv")
df.shape

(200, 4)

In [9]:
df.head(100)

TV  Radio  Newspaper  Sales
0   230.1   37.8       69.2   22.1
1    44.5   39.3       45.1   10.4
2    17.2   45.9       69.3   12.0
3   151.5   41.3       58.5   16.5
4   180.8   10.8       58.4   17.9
..    ...    ...        ...    ...
95  163.3   31.6       52.9   16.9
96  197.6    3.5        5.9   16.7
97  184.9   21.0       22.0   20.5
98  289.7   42.3       51.2   25.4
99  135.2   41.7       45.9   17.2

[100 rows x 4 columns]

In [5]:
df.drop("Unnamed: 0",axis=1,inplace=True)

KeyError: "['Unnamed: 0'] not found in axis"

In [6]:
df.corr()

TV     Radio  Newspaper     Sales
TV         1.000000  0.054809   0.056648  0.901208
Radio      0.054809  1.000000   0.354104  0.349631
Newspaper  0.056648  0.354104   1.000000  0.157960
Sales      0.901208  0.349631   0.157960  1.000000

In [7]:
X=df[['TV', 'Radio', 'Newspaper']]
X.head()

TV  Radio  Newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [10]:
Y=df['Sales']
Y

0      22.1
1      10.4
2      12.0
3      16.5
4      17.9
       ... 
195     7.6
196    14.0
197    14.8
198    25.5
199    18.4
Name: Sales, Length: 200, dtype: float64

In [11]:
X.shape

(200, 3)

In [12]:
X=df[['TV','Radio','Newspaper']]
Y=df['Sales']
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [13]:
X_train.shape

(160, 3)

In [14]:
X_test.shape

(40, 3)

In [15]:
Y_train.shape

(160,)

In [16]:
Y_test.shape

(40,)

In [17]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,Y_train)

LinearRegression()

In [18]:
regressor.coef_

array([ 0.05413652,  0.10730169, -0.00119236])

In [19]:
regressor.intercept_

4.719373092792816

In [17]:
#y=(0.04627757*x1)+(0.19143052*x2)+(-0.00599346*x3)

In [20]:
regressor.predict(X_test)

array([19.45137492, 13.80430336, 23.38180709, 24.88053694, 15.08143245,
       20.70897819, 11.29162956, 12.29893818, 13.78224887, 12.93954233,
       12.18114267, 21.38319186, 10.93532608, 12.11315895,  7.00217541,
        8.08038366, 10.6753559 , 17.07456282, 15.7312971 ,  8.78422426,
       18.20788492, 18.86090035, 19.30486815, 24.54018141, 21.68950073,
       18.03716843, 21.06961888, 24.81739889, 15.18946237, 17.28286344,
        9.88309678,  8.3380524 , 10.10662507, 22.13768674, 14.72839172,
       11.26094958, 20.02915197, 23.09033716,  9.18213965, 12.47774802])

In [21]:
Y_pred_train=regressor.predict(X_train)

In [22]:
Y_pred_test=regressor.predict(X_test)

In [23]:
Y_pred_test

array([19.45137492, 13.80430336, 23.38180709, 24.88053694, 15.08143245,
       20.70897819, 11.29162956, 12.29893818, 13.78224887, 12.93954233,
       12.18114267, 21.38319186, 10.93532608, 12.11315895,  7.00217541,
        8.08038366, 10.6753559 , 17.07456282, 15.7312971 ,  8.78422426,
       18.20788492, 18.86090035, 19.30486815, 24.54018141, 21.68950073,
       18.03716843, 21.06961888, 24.81739889, 15.18946237, 17.28286344,
        9.88309678,  8.3380524 , 10.10662507, 22.13768674, 14.72839172,
       11.26094958, 20.02915197, 23.09033716,  9.18213965, 12.47774802])

In [24]:
Y_pred_train

array([ 9.45162584, 14.28399094,  8.64895954, 19.91748433, 15.78955703,
       20.88666252, 10.64348508, 19.30417022, 16.63639676, 23.58396711,
       14.58254357, 13.46624059, 16.44964333, 14.41020222,  9.2553405 ,
       20.52107711, 17.10854191, 17.09496215, 18.91395549, 15.29181248,
       10.7806375 , 17.09324915, 10.34798678, 14.13316699, 15.38933191,
       20.15941242,  9.25830828, 11.6937691 ,  9.69553541, 11.79788946,
       13.15478866, 16.88752522, 23.56108901, 20.71628983,  8.89129211,
       24.90698874, 20.85119199, 21.1496801 , 16.37472462, 16.57540725,
       12.3672116 , 12.1601799 , 12.50786941, 17.8392701 , 14.00958424,
        6.17923601, 10.33515385, 15.59648128, 20.86178005, 16.83033048,
       17.67810191, 10.50174129, 20.17370244,  8.2088227 ,  9.8757607 ,
        9.06167199, 19.33628284, 18.73524255, 10.21676756, 23.86226358,
       15.78527125, 11.78170865,  5.44095792, 12.50459763, 12.63506982,
       10.59513891, 12.14830231, 15.81091893,  9.68817523,  7.91

In [25]:
Y_train

65     11.3
77     14.2
170     8.4
178    16.8
9      15.6
       ... 
168    17.1
166     8.0
53     21.2
17     24.4
76      6.9
Name: Sales, Length: 160, dtype: float64

In [26]:
X_train.head()

TV  Radio  Newspaper
65    69.0    9.3        0.9
77   120.5   28.5       14.2
170   50.0   11.6       18.4
178  276.7    2.3       23.7
9    199.8    2.6       21.2

In [27]:
y=(0.04611906*175.7)+(0.1899*15.4)+(-0.0011344*2.4)+2.954880862443101
y

13.979737144443101

In [28]:
y=(0.04611906*287.6)+(0.1899*43.0)+(-0.0011344*71.8)+2.954880862443101
y

24.302972598443105

In [27]:
# 15.59458137 value it predicted

In [28]:
# How are my predictions perfect to what level predictions also have some error know 

In [30]:
Y_test

20     18.0
67     13.4
61     24.2
98     25.4
123    15.2
184    17.6
1      10.4
73     11.0
159    12.9
157    10.1
16     12.5
176    20.2
82     11.3
151    11.6
189     6.7
56      5.5
125    10.6
85     20.2
89     16.7
44      8.5
153    16.0
23     20.5
62     20.7
101    23.8
188    20.9
40     16.6
39     21.5
183    26.2
120    15.5
3      16.5
149    10.1
182     8.7
32     13.2
47     23.2
177    16.7
190    10.8
92     19.4
147    25.4
129     9.7
115    12.6
Name: Sales, dtype: float64

In [31]:
Y_pred_test

array([19.45137492, 13.80430336, 23.38180709, 24.88053694, 15.08143245,
       20.70897819, 11.29162956, 12.29893818, 13.78224887, 12.93954233,
       12.18114267, 21.38319186, 10.93532608, 12.11315895,  7.00217541,
        8.08038366, 10.6753559 , 17.07456282, 15.7312971 ,  8.78422426,
       18.20788492, 18.86090035, 19.30486815, 24.54018141, 21.68950073,
       18.03716843, 21.06961888, 24.81739889, 15.18946237, 17.28286344,
        9.88309678,  8.3380524 , 10.10662507, 22.13768674, 14.72839172,
       11.26094958, 20.02915197, 23.09033716,  9.18213965, 12.47774802])

In [31]:
# Errors with General Example Adjusted R square lies between 0 and 1

In [32]:
#MAE
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [33]:
mse_train=mean_squared_error(Y_train,Y_pred_train)
mse_test=mean_squared_error(Y_test,Y_pred_test)
print(mse_train,"  ",mse_test)

2.299323976485044    4.740851927514633


In [33]:
mae_train=mean_absolute_error(Y_train,Y_pred_train)
mae_test=mean_absolute_error(Y_test,Y_pred_test)
print(mae_train,"  ",mae_test)

1.2737546793559429    1.0977693645484323


In [34]:
rmse_train=np.sqrt(mean_squared_error(Y_train,Y_pred_train))
rmse_test=np.sqrt(mean_squared_error(Y_test,Y_pred_test))
print(rmse_train,"  ",rmse_test)

1.6981349805370591    1.415916362195238


In [35]:
r2_score_train=r2_score(Y_train,Y_pred_train)
r2_score_test=r2_score(Y_test,Y_pred_test)
print(r2_score_train,"  ",r2_score_test)

0.8929129891313564    0.9347113314640897


In [36]:
n_train=X_train.shape[0]
n_train

160

In [37]:
n_test=X_test.shape[0]
n_test

40

In [38]:
p=len(X_train.columns)
p

3

In [39]:
adj_r2_score_train=1-(((1-r2_score_train)*(n_train-1))/(n_train-p-1))
adj_r2_score_test=1-(((1-r2_score_test)*(n_test-1))/(n_test-p-1))
print(adj_r2_score_train*100,"   ",adj_r2_score_test*100)

89.08536235377287     92.92706090860972


# Task exclude News paper Column and do the same and say whether They are useful or not

In [40]:
X=df[['TV', 'Radio']]
X.head()

TV  Radio
0  230.1   37.8
1   44.5   39.3
2   17.2   45.9
3  151.5   41.3
4  180.8   10.8

In [41]:
Y=df['Sales']
Y

0      22.1
1      10.4
2      12.0
3      16.5
4      17.9
       ... 
195     7.6
196    14.0
197    14.8
198    25.5
199    18.4
Name: Sales, Length: 200, dtype: float64

In [42]:
X.shape

(200, 2)

In [43]:
X=df[['TV','Radio']]
Y=df['Sales']
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [44]:
X_train.shape

(160, 2)

In [45]:
X_test.shape

(40, 2)

In [46]:
Y_train.shape

(160,)

In [47]:
Y_test.shape

(40,)

In [48]:
from sklearn.linear_model import LinearRegression
regressor1=LinearRegression()
regressor1.fit(X_train,Y_train)

LinearRegression()

In [51]:
regressor1.coef_

array([0.0546951 , 0.10305616])

In [50]:
regressor1.intercept_

4.626343287049272

In [52]:
regressor1.predict(X_test)

array([ 9.33235562, 13.80304151, 16.6761185 , 20.94873909, 18.51094674,
       23.53948024, 18.21339311, 10.61181868, 10.52389546, 17.08966992,
       13.72652835, 11.15155355, 12.11012212, 17.07256801, 10.13671589,
       20.59617292, 24.57890949, 13.45954195, 15.14597371, 11.94338325,
       17.82155736, 20.70305584, 20.75980475, 15.92656451,  7.88890965,
       10.04572805,  9.49120253, 17.14092446, 22.97794339, 20.9927775 ,
       17.74945169, 13.00312385,  8.88749385, 12.55153454, 13.29399236,
       16.52221887, 22.11089367, 12.34091086, 18.85488369,  9.73530154])

In [53]:
Y_pred_train=regressor1.predict(X_train)

In [54]:
Y_pred_test=regressor1.predict(X_test)

In [55]:
Y_pred_test

array([ 9.33235562, 13.80304151, 16.6761185 , 20.94873909, 18.51094674,
       23.53948024, 18.21339311, 10.61181868, 10.52389546, 17.08966992,
       13.72652835, 11.15155355, 12.11012212, 17.07256801, 10.13671589,
       20.59617292, 24.57890949, 13.45954195, 15.14597371, 11.94338325,
       17.82155736, 20.70305584, 20.75980475, 15.92656451,  7.88890965,
       10.04572805,  9.49120253, 17.14092446, 22.97794339, 20.9927775 ,
       17.74945169, 13.00312385,  8.88749385, 12.55153454, 13.29399236,
       16.52221887, 22.11089367, 12.34091086, 18.85488369,  9.73530154])

In [56]:
Y_pred_train

array([20.98204327,  6.89612118, 18.13654643, 12.47272766,  7.75864345,
        5.38407156, 21.26765585, 15.87389835, 17.13372588, 11.10707045,
       17.12538046, 22.57471514,  7.89092982, 18.86897218, 18.08694342,
        5.31313908, 21.76228299, 10.00494297, 11.55664837, 20.48667155,
       18.68135731, 10.74234234, 19.19075754, 14.86517091, 11.63362379,
        9.0128903 , 16.8084312 , 15.55794966, 16.95060335, 15.62822387,
       16.48299901,  8.55654973,  8.88442045, 18.03628865, 12.47687039,
       12.59459724,  7.33632677, 14.24515609,  9.06904823, 18.83345913,
       10.14163684,  9.49302522, 13.72592128, 17.36145878, 17.80273516,
       24.78806887, 14.15420336, 19.37486309, 10.93487085, 12.9534872 ,
       21.18954235, 14.05449415,  6.29534839,  7.92149559, 15.30428962,
        9.06184965, 15.77756095, 14.71441343, 14.56869685,  9.86882985,
       20.2295446 , 18.84272906,  7.12733854, 17.83530354, 14.73928734,
       13.22059502, 13.73968502,  5.98962926, 19.98584787, 18.16

In [57]:
Y_train

39     21.5
189     6.7
21     17.5
186    10.3
60      8.1
       ... 
133    19.6
36     25.4
198    25.5
22      5.6
134    10.8
Name: Sales, Length: 160, dtype: float64

In [58]:
Y_test

24      9.7
37     14.7
103    19.7
35     17.8
146    18.2
42     20.7
113    20.9
125    10.6
18     11.3
85     20.2
114    14.6
6      11.8
151    11.6
154    20.6
29     10.5
55     23.7
101    23.8
180    15.5
19     14.6
94     11.5
110    18.4
184    17.6
52     22.6
160    16.4
132     5.7
136     9.5
49      9.7
174    16.5
147    25.4
102    19.8
41     17.1
161    13.3
117     9.4
164    11.9
63     14.0
45     16.1
93     22.2
115    12.6
23     20.5
38     10.1
Name: Sales, dtype: float64

In [59]:
Y_pred_test

array([ 9.33235562, 13.80304151, 16.6761185 , 20.94873909, 18.51094674,
       23.53948024, 18.21339311, 10.61181868, 10.52389546, 17.08966992,
       13.72652835, 11.15155355, 12.11012212, 17.07256801, 10.13671589,
       20.59617292, 24.57890949, 13.45954195, 15.14597371, 11.94338325,
       17.82155736, 20.70305584, 20.75980475, 15.92656451,  7.88890965,
       10.04572805,  9.49120253, 17.14092446, 22.97794339, 20.9927775 ,
       17.74945169, 13.00312385,  8.88749385, 12.55153454, 13.29399236,
       16.52221887, 22.11089367, 12.34091086, 18.85488369,  9.73530154])

In [60]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [61]:
mse_train=mean_squared_error(Y_train,Y_pred_train)
mse_test=mean_squared_error(Y_test,Y_pred_test)
print(mse_train,"  ",mse_test)

2.7317157831419667    2.644095696076887


In [62]:
mae_train=mean_absolute_error(Y_train,Y_pred_train)
mae_test=mean_absolute_error(Y_test,Y_pred_test)
print(mae_train,"  ",mae_test)

1.2515443527003556    1.2199686685128448


In [63]:
rmse_train=np.sqrt(mean_squared_error(Y_train,Y_pred_train))
rmse_test=np.sqrt(mean_squared_error(Y_test,Y_pred_test))
print(rmse_train,"  ",rmse_test)

1.6527903022289205    1.626067555815836


In [64]:
r2_score_train=r2_score(Y_train,Y_pred_train)
r2_score_test=r2_score(Y_test,Y_pred_test)
print(r2_score_train,"  ",r2_score_test)

0.9050971033639521    0.8862808341937849


In [65]:
n_train=X_train.shape[0]
n_train

160

In [66]:
n_test=X_test.shape[0]
n_test

40

In [67]:
p=len(X_train.columns)
p

2

In [68]:
adj_r2_score_train=1-(((1-r2_score_train)*(n_train-1))/(n_train-p-1))
adj_r2_score_test=1-(((1-r2_score_test)*(n_test-1))/(n_test-p-1))
print(adj_r2_score_train*100,"   ",adj_r2_score_test*100)

90.38881492666776     88.01338522583137
